### ISSUE TITLE
Unable to create library directory /config/deps

### ISSUE THREAD

**Issue by kenske** [tribut/homeassistant-docker-venv#10]
Thanks for this script!

I'm trying to get it set up, but I'm running into this error message on start:

```
...
homeassistant    | [03:41:48] INFO: Creating user homeassistant with 1000:1000
homeassistant    | [03:41:48] INFO: Initializing venv in /var/tmp/homeassistant-venv
homeassistant    | [03:41:52] INFO: Activating venv
homeassistant    | [03:41:52] INFO: Starting homeassistant
homeassistant    | Fatal Error: Unable to create library directory /config/deps
```

Any ideas why? Am I doing something wrong? Here is my docker-compose file:

```
version: '3'

services:
  homeassistant:
    container_name: homeassistant
    restart: always
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./venv/run:/etc/services.d/home-assistant/run
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
```
