### ISSUE TITLE
Not working on 0.117.0

### ISSUE THREAD

**Issue by StefanNienhuis** [tribut/homeassistant-docker-venv#15]
On the new Home Assistant 0.117.0, I'm getting this error message:
`s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted`

It seems like something changed in S6.

**Comment by tribut** [comment]
Thank you for reporting this, but unfortunately I cannot reproduce it. Can you give me the full `docker run` command you are using and maybe some more context for the error message? Thanks!

**Comment by StefanNienhuis** [comment]
Hi, this is my docker compose service:
```yml
homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    userns_mode: host
    network_mode: host
    privileged: true
    restart: unless-stopped

    volumes:
      - /home/<username>/Docker/Home Assistant:/config
      - /home/<username>/Docker/Home Assistant/docker/run:/etc/services.d/home-assistant/run

    devices:
      - /dev/ttyACM0:/dev/ttyACM0

    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 998
      EXTRA_GID: 20 107

    labels:
      com.centurylinklabs.watchtower.enable: 'true'
```

When using tag stable, it repeatedly logs `s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted`, nothing else.
When using tag 0.16.4, it runs fine.
