### ISSUE TITLE
ocker home-assistant doesn't start due to Operation not permitted / permissions denied

### ISSUE THREAD

**Issue by miodzicho** [tribut/homeassistant-docker-venv#31]
docker home-assistant doesn't start due to Operation not permitted / permissions denied

`version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
        - TZ=Europa/Berlin
       - PUID=1000
        - PGID=1000
        - UMASK=007
        - PACKAGES=iputils
#    privileged: true
    volumes:
      # Local path where your home assistant config will be stored
      - /home/user/homeautomation-config:/config
     - /home/user/homeautomation-config/docker/run:/etc/services.d/home-assistant/run
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      # MariaDB is optional (only if you would like to use a different database for HA).
      - mariadb
      # Deconz is optional (only if you use the deconz Zigbee hub).
      - deconz
    user: "${LOCAL_USER}:${LOCAL_USER}"`

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/home-assistant/run: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/home-assistant/run: Operation not permitted
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/home-assistant/finish: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/home-assistant/finish: Operation not permitted
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
s6-supervise home-assistant: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
[services.d] done.
s6-supervise home-assistant: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied`

**Comment by tribut** [comment]
Hey, thanks for getting in touch.

You are using the `user` keyword in your `docker-compose.yml`, which will not work.

Recent home-assistant images need root-permissions inside the container on startup. The run script will then drop privileges to `$PUID:PGID` just before starting home-assistant.

So just remove the `user` line and you should be good.

**Comment by MaxVRAM** [comment]
I was having the same issue after following a Docker-Compose guide that included `user=` then attempted to add UID/GID from this repo.

Can confirm that removing the `user=` line worked perfectly! Thank you.

The guide I mentioned:
[](https://www.wouterbulten.nl/blog/tech/home-automation-setup-docker-compose/)

Working `docker-compose.yaml` (truncated):

```
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    #user: "${LOCAL_USER}:${LOCAL_USER}"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=007
      - PACKAGES=iputils
    ports:
      - "${SERVER_PORT}:8123"
    network_mode: host
    depends_on:
      - mariadb
    volumes:
      - /srv/ha/config:/config
      - /srv/ha/docker/run:/etc/services.d/home-assistant/run
      - /etc/localtime:/etc/localtime:ro
 ```
